swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad document processing pipeline APIs
  description: The specification defines various modules that participate in the orchestration of document processing flow. The document processing leverages various CV technique to achieve the desired results.
  contact:
    name: KD, Dhiraj, Naresh
    email: kumar.deepak@tarento.com

schemes:
  - https
basePath: '/document-processor'

paths:
  /evaluator/v0/process:
    post:
      summary: The method compares 
      parameters:
        - name: filename
          in: body
          required: true
          schema:
            $ref: '#/definitions/EvaluatorRequest'
      tags:
      - Evaluator
      responses:
        200:
          description: On successful completion of the job.
          schema:
            $ref: '#/definitions/HttpOutputSuccess'
        400:
          description: On errors causing a failure in the job.
          schema:
            $ref: '#/definitions/HttpOutputError'

definitions:

  EvaluatorRequest:
    type: object
    properties:
      inputs:
        type: array
        description: array of word detector
        items:
          type: string
          $ref: '#/definitions/EvaluatorInput'

  EvaluatorResponse:
    type: object
    properties:
      inputs:
        type: array
        description: array of word detector input object
        items:
          $ref: '#/definitions/EvaluatorInput'
      outputs:
        type: array
        description: array of word detector output object
        items:
          $ref: '#/definitions/EvaluationOutput'
    required:
      - outputs
        
  EvaluationOutput:
    type: object
    properties:
      input:
        type: object
        description: file object on which evaluation is required
        $ref: '#/definitions/File'
      ground:
        type: object
        description: file object on which input evaluation is compared against
        $ref: '#/definitions/File'
      pages:
        type: array
        description: page wise boxes comparision
        items:
          $ref: '#/definitions/PageCompare'
      status:
        type: object
        description: operation result for the file that is processed
        $ref: '#/definitions/ErrorCode'

  EvaluatorInput:
    type: object
    properties:
      input:
        type: object
        description: file object on which evaluation is required
        $ref: '#/definitions/File'
      ground:
        type: object
        description: file object on which input evaluation is compared against
        $ref: '#/definitions/File'
      config:
        type: object
        description: configuration parameters that will be applied for evalution
        $ref: '#/definitions/EvaluateConfig'
    required:
      - input
      - ground
      - config
  
  PageCompare:
    type: object
    properties:
      regions:
        type: array
        description: region comparision results for a given page
        items:
          $ref: '#/definitions/RegionCompare'

  RegionCompare:
    type: object
    properties:
      input:
        type: object
        description: region detected on input file
        $ref: '#/definitions/Region'
      ground:
        type: object
        description: region detected on ground truth information
        $ref: '#/definitions/Region'
      comparision:
        type: object
        description: comparision result of input and ground
        $ref: '#/definitions/Comparision'
  
  Comparision:
    type: object
    description: comparision result of OCR and IOU strategies, one of the following key will be valid based upon choosen strategies
    properties:
      iou:
        type: object
        description: comparision result when strategy is IOU
        $ref: '#/definitions/AreaCompare'
      ocr:
        type: object
        description: comparision result when strategy is OCR
        $ref: '#/definitions/TextCompare'
  
  AreaCompare:
    type: object
    properties:
      error_percentage:
        type: number
        description: region overlapping percentage
      input_area:
        type: number
        description: input region area
      ground_area:
        type: number
        description: ground region area
    required:
      - error_percentage
      - input_area
      - ground_area
      
  TextCompare:
    type: object
    properties:
      input_text:
        type: string
        description: textual data of detected region
      ground_text:
        type: number
        description: textual data present in the ground truth
      error_percentage:
        type: number
        description: incorrectly detected characters divided by ground text length
    required:
      - input_text
      - ground_text
      - error_percentage
    

  File:
    type: object
    properties:
      identifier:
        type: string
        description: unique identifier, uuid-v4
      jobId:
        type: string
        description: system wide unique identifier that is generated by WFM pipeline
      name:
        type: string
        description: human readable name of file
      format:
        type: string
        description: allowed file format
        enum: ['PDF', 'PNG', 'JPEG', 'BMP']
    required:
      - identifier
      

  OCR:
    type: object
    properties:
      option:
        type: string
        description: ocr configuration settings
        enum: ['HIGH_ACCURACY', 'MEDIUM_ACCURACY', 'LOW_ACCURACY']
      language:
        type: string
        description: indic language code as per ISO 639-1
        enum: ['hi','ma','ta', 'ml', 'ka']

  EvaluateConfig:
    type: object
    properties:
      strategy:
        type: string
        description: evaluation strategy to arrived at result
        enum: ['IOU', 'TEXT']
      boxLevel:
        type: string
        description: evaluation strategy has to be applied at a given classified level
        enum: ['WORD', 'LINE', 'PARAGRAPH', 'IMAGE', 'TABLE', 'LIST']

  Point:
    type: object
    properties:
      x:
        type: integer
        description: x-coordinate
      y:
        type: integer
        description: y-coordinate
      confidence:
        type: number
        description: detection confidence
    required:
      - x
      - y
      - confidence

  Polygon:
    type: object
    properties:
      vertices:
        type: array
        description: polygon that is enclosing the identification area
        items:
          $ref: '#/definitions/Point'

  Font:
    type: object
    properties:
      family:
        type: string
        description: font family
      size:
        type: number
        description: font size
      style:
        type: string
        description: font style like BOLD, ITALIC, REGULAR
        enum: ['BOLD', "ITALIC", 'REGULAR']

  Line:
    type: object
    description: a group of related words
    properties:
      identifier:
        type: string
        description: unique identifier, uuidv4
        format: uuid
      boundingBox:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      class:
        type: string
        description: though not grammatical however used extensively in document writings
        enum: ['HEADER', 'FOOTER','TEXT']
      font:
        type: object
        description: font property
        $ref: '#/definitions/Font'

  Word:
    type: object
    description: a language script that can be written together and generates a meaning
    properties:
      identifier:
        type: string
        description: word level identifier
        format: uuid
      boundingBox:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      class:
        type: string
        description: though not grammatical however used extensively in document writings
        enum: ['SUPERSCRIPT', 'SUBSCRIPT']
      text:
        type: string
        description: the textual payload
      language:
        type: string
        description: indic language code as per ISO 639-1
        enum: ['hi','ma','ta', 'ml', 'ka']
      confidence:
        type: number
        description: detectiong confidence
    required:
      - identifier
      - boundingBox

  Region:
    type: object
    description: the group of related lines object
    properties:
      identifier:
        type: string
        description: unique identifier, uuidv4
        format: uuid
      boundingBox:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      class:
        type: string
        description: category of block
        enum: ['LINE', 'HEADER', 'FOOTER', 'FOOTNOTE', 'TABLE', 'IMAGE', 'BULLETS', 'BACKGROUND']
    required:
      - identifier
      - boundingBox

  Page:
    type: object
    properties:
      identifier:
        type: string
        description: page identifier
        format: uuid
      vertices:
        type: object
        description: positional information of bounding box
        $ref: '#/definitions/Polygon'
      resolution:
        type: number
        description: resolution of page image
      regions:
        type: array
        description: list of region present in a page
        items:
          $ref: '#/definitions/Region'
      lines:
        type: array
        description: list of lines present in a page
        items:
          $ref: '#/definitions/Line'
      words:
        type: array
        description: list of words present in a page
        items:
          $ref: '#/definitions/Word'
    required:
      - identifier
      - vertices
      - resolution

  ErrorCode:
    type: object
    properties:
      code:
        type: integer
        description: status code
      message:
        type: string
        description: human understandable format
    required:
      - code
      - message

  HttpOutputSuccess:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      status:
        type: object
        description: overall operation status
      data:
        type: object
        description: the return value should be returned under this property
        $ref: '#/definitions/EvaluatorResponse'

  HttpOutputError:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      status:
        type: object
        description: overall operation status
        $ref: '#/definitions/ErrorCode'
      data:
        type: integer
        description: should be null object
        default: null

responses:
  ERROR_MISSING_MANDATORY_PARAMETERS:
    description: Input request does not have parameters are the required.
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_UNAUTHORIZED:
    description: request does not have relevant authority to start the process.
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_INVALID_FILE_FORMAT:
    description: provided file data is invalid, choose from the given list
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_WORD_DETECTION:
    description: model detected error while executing its purpose
    schema:
      $ref: '#/definitions/ErrorCode'
  ERROR_RESOURCE_EXHAUSTED:
    description: application deprived of system resources
    schema:
      $ref: '#/definitions/ErrorCode'
  SUCCESS:
    description: all good
    schema:
      $ref: '#/definitions/ErrorCode'