services:
  mongodb:
    image: mongo:5.0.18
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  workflow-manager:
    image: workflow-manager:1.0
    depends_on:
      - mongodb
      - redis
      - kafka
    environment:
      - KAFKA_HOSTS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongodb:27017

  anuvaad-ocr:
    image: anuvaad-ocr:2.1
    ports:
      - "5000:5000"
    depends_on:
      - workflow-manager

  nmt-inference:
    image: nmt-inference:1.2
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  aligner-service:
    image: aligner-service:1.0
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch

volumes:
  mongodb_data: 