openapi: 3.0.0
info:
  title: OCR - Content Handler
  description: A python based microservice to trigger and control the content handler part of anuvaad document digitizer 
  contact:
    name: Jainy Joy
    email: jainy.joy@tarento.com
  version: 1.0.0
servers:
  - url: https/anuvaad/ocr-content-handler
paths:
  /v0/ocr/save-document:
    post:
      tags:
        - Save Document
      summary: API to save digitized document content.
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/DocumentRequest"
        required: true
      responses:
        "200":
          description: On successful completion of the request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Response"
        "400":
          description: On input errors causing a failure in the request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      
      
  /v0/ocr/update-document:
    post:
      tags:
        - Update Document
      summary: API to update digitized document content.
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/WordUpdateRequest"
        required: true
      responses:
        "200":
          description: On successful completion of the request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/WordUpdateResponse"
        "400":
          description: On input errors causing a failure in the request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    
      
  /v0/ocr/fetch-document:
    get:
      tags:
        - Fetch Document
      parameters:
        - in: query
          name: recordID
          schema:
            type: string
          required: true
        - in: query
          name: start_page
          schema:
            type: string
          required: true
        - in: query
          name: end_page
          schema:
            type: string
          required: true
      responses:
        "200":
          description: On successful completion of the request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Response"
        "400":
          description: On input errors causing a failure in the request.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
 
      
components:
  schemas:
    DocumentRequest:
      type: object
      properties:
        files:
          type: array
          description: a list of objects having file, file_config and its pages
          items:
            type: object
            properties:
              file:
                $ref: "#/components/schemas/File"
              file_config:
                $ref: "#/components/schemas/FileConfig"
              pages:
                type: array
                description: page level paragraph, line, word  and symbol information
                items:
                  $ref: "#/components/schemas/Page"
    
    File:
      type: object
      properties:
        name:
          type: string
          description: name of input file
        type:
          type: string
          description: type of input file
        identifier:
          type: string
          description: unique identifier for a file generated by the file converter module.
    
    FileConfig:
      type: object
      properties:
        languages:
          type: array
          description: list of ISO 639-1  language code
          items:
            type: string
    
    Page:
      type: object
      properties:
        identifier:
          type: string
          description: unique page identifier
        boundingbox:
          type: object
          $ref:  "#/components/schemas/Vertices"
          description: page coordinates
        path:
          type: string
          description: optional placeholder to hold image path of the page
        resolution:
          type: integer
          description: dpi of the page image
        regions:
          type: array
          description: coordinates of extracted regions
          items:
            $ref: "#/components/schemas/Region"
    
    Region:
      type: object
      properties:
        boundingbox:
          type: object
          $ref:  "#/components/schemas/Vertices"
          description: region coordinates
        identifier:
          type: string
          description: unique identifier for region
          format: uuid4
        class:
          type: string
          description: class of detected region
          enum:
            - PARA
            - LINE
            - IMAGE
            - TABLE
            - TABLE_CELL
            - SEPARATOR
            - MATHEMATICAL_FORMULA
            - HEADER
            - FOOTER
            - BGIMAGE
        path:
          type: string
          description: optional placeholder to hold image path of the region
        regions:
          type: array
          description: various visual objects present on the page
          items:
              oneOf:
                - $ref: '#/components/schemas/Region'
                - $ref: '#/components/schemas/DataRegion'
      required:
        - boundingbox
        - identifier
        - class
        - regions
    
    DataRegion:
      type: object
      required:
        - boundingbox
        - identifier
        - confidence
        - class
        - text
        - font
      properties:
        boundingbox:
          type: object
          $ref:  "#/components/schemas/Vertices"
          description: region coordinates extracted
        identifier:
          type: string
          description: unique identifier for region
          format: uuid4
        language:
          type: string
          description: language of the extracted text
        confidence:
          type: number
          description: confidence of the extracted text
        class:
          type: string
          description: class of detected region
          enum:
            - WORD
            - SYMBOL
            - SUPERSCRIPT
            - SUBSCRIPT
        text:
          type: string
          description: collated text at region level or class specific metadata
        font:
          $ref: "#/components/schemas/Font"
      
  
    Vertices:
      type: array
      description: list of vertex object
      items:
        $ref: '#/components/schemas/Vertex'
    
    Vertex:
      type: object
      description: coordinate of a point, X & Y
      required:
        - x
        - y
      properties:
        x:
          type: number
        y:
          type: number
      
    Font:
      type: object
      properties:
        family:
          type: string
          description: font family
        size:
          type: number
          description: font size
        style:
          type: string
          description: font style like BOLD, ITALIC, REGULAR
          enum:
            - BOLD
            - ITALIC
            - REGULAR
    
    WordUpdateRequest:
      type: object 
      properties:
        words:
          type: array
          description: a list of objects having word details to update
          items:
            type: object
            properties:
              record_id:
                type: string
              region_id:
                type: string
                description: identifier of the parent region
              word_id:
                type: string
                description: identifier of the word level region
              updated_word:
                type: string
                description: new word, which will be replcing the old word
      
    WordUpdateResponse:
      type: object 
      properties:
        count:
          type: integer
        message:
          type: string
        status:
          type: boolean
        data:
          type: array
          description: a list of objects having word details which were updated
          items:
            type: object
            properties:
              record_id:
                type: string
              region_id:
                type: string
                description: identifier of the parent region
              word_id:
                type: string
                description: identifier of the word level region
              updated_word:
                type: string
                description: new word, which will be replcing the old word
            
        
        
    
    Response:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        data:
          type: array
          items: 
            type: object
            $ref:  "#/components/schemas/Page"
        count:
          type: integer
    
    ErrorResponse:
      type: object
      properties:
        errorID:
          type: string
        code:
          type: string
        message:
          type: string
        timeStamp:
          type: integer
        errorType:
          type: string
        
    
  
          
