swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad Tesseract OCR
  description: A python based microservice to trigger and orchestrate text extraion given eihter a file and coordinates or only an file
  contact:
    name: Naresh & Dhiraj, dhiraj.daga@tarento.com
    email: naresh.kumar@tarento.com
schemes:
  - https
basePath: '/api'
paths:
  /v0/ocr/tesseract:
    post:
      summary: API to extract text from image file.
      parameters:
        - name: filename
          in: body
          required: true
          schema:
            $ref: '#/definitions/TesseractOcrRequest'
      tags:
      - Tesseract OCR
      responses:
        200:
          description: On successful completion of the job.
          schema:
            $ref: '#/definitions/TesseractOcrResponse'
        400:
          description: On input errors causing a failure in the job.
          schema:
            $ref: '#/definitions/Error'
definitions:
  TesseractOcrRequest:
    type : object
    properties:
      input :
        type : object
        properties:
          files:
            type: array
            description : a list of objets having file, file_config and pages
            items:
              type: object
              properties:
                file:
                  type: object
                  $ref : '#/definitions/File'
                file_config:
                  type: object
                  $ref : '#/definitions/FileConfig'

                cooradinates :
                  type : array
                  description: page level word and line coordinates
                  items :
                    $ref: '#/definitions/Coordinates'

  TesseractOcrResponse:
    type : object
    properties:
      output :
        type : object
        properties:
          files:
            type: array
            description : a list of objets having file, file_config and pages
            items:
              type: object
              properties:
                file:
                  type: object
                  $ref : '#/definitions/File'
                file_config:
                  type: object
                  $ref : '#/definitions/FileConfig'

                ocr :
                  type : array
                  description: page level word and line coordinates
                  items :
                    $ref: '#/definitions/OcrOutput'






  File:
    type: object
    properties :
      name :
        type: string
        description: name of input file
      type :
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file


  FileConfig:
    type: object
    properties:
      language :
        type : string
        description: 'ISO 639-1  language code'
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'


  PageInput:
    type: object
    properties :
      path :
        type: string
        description: name of input file
      type :
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file
      language :
        type : string
        description: 'ISO 639-1  language code'
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'
      coordinates :
        type : array
        description: if given ocr will be performed only on the coordinates, else on entire page
        items :
          $ref: '#/definitions/Coordinates'




  PageRespone:
    type: object
    properties :
      path :
        type: string
        description: name of input file
      type :
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file
      language :
        type : string
        description: 'ISO 639-1  language code'
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'

  OcrOutput :
    type : object
    properties:
      pages:
        type: array
        items:
          type: object
          properties:
            regions:
              type: array
              items:
                allOf:
                - $ref: '#/definitions/Coordinates'
                properties:
                  identifier:
                    type: string
                  text:
                    type: string
                  words:
                    type: array
                    description: word level text,coordinates and confidence
                    items:
                     allOf:
                     - $ref: '#/definitions/Coordinates'
                     properties:
                      identifier:
                        type: string
                      text:
                        type: string

  Coordinates:
    type: object
    properties:
      top:
        type: integer
        description: y co-ordinate of the bounding box
      left:
        type: integer
        description: x co-ordinate of the bounding box
      width:
        type: integer
        description: width of the bounding box
      height:
        type: integer
        description: height of bounding box
      confidence:
        type: number
        description: detection confidence


  OcrConfig:
    type: object
    description: configuration for tuning speed and accuracy of ocr mdoule
    properties:
      level:
        type: string
        enum: ['PAGE','LINE','BLOCK' ]
      mode:
        type: string
        enum: ['ACCURRATE','FAST']

  HttpOutput:
    type: object
    properties:
      status:
        type: number
        description: Status code.
  Error:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      http:
        type: object
        description: Final output of this process.
        items:
          $ref: '#/definitions/HttpOutput'
