swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad Google OCR
  description: A python based microservice to trigger and orchestrate text extraion given eihter an image and coordinates or only an image
  contact:
    name: Naresh & Dhiraj, dhiraj.daga@tarento.com
    email: naresh.kumar@tarento.com
schemes:
  - https
basePath: '/api'
paths:
  /v0/ocr/google:
    post:
      summary: API to extract text from image file.
      parameters:
        - name: filename
          in: body
          required: true
          schema:
            $ref: '#/definitions/GoogleOcrRequest'
      tags:
      - Google OCR
      responses:
        200:
          description: On successful completion of the job.
          schema:
            $ref: '#/definitions/GoogleOcrResponse'
        400:
          description: On input errors causing a failure in the job.
          schema:
            $ref: '#/definitions/Error'
definitions:
  GoogleOcrRequest:
    type : object
    properties:
      files :
        type : array
        description : a list of objets having file name, type and language.
        items :
          $ref : '#/definitions/PageRequest'
          
          
  GoogleOcrResponse:
    type : object
    properties:
      files :
        type : array
        description : a list of file level results
        items :
         $ref: '#/definitions/PageRespone'

  PageRequest:
    type: object
    properties :
      path : 
        type: string
        description: name of input file
      type : 
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file
      language :
        type : string
        description: 'ISO 639-1  language code' 
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'
      coordinates :
        type : array
        description: if given ocr will be performed only on the coordinates, else on entire page
        items :
          $ref: '#/definitions/Coordinates'
          
  
 
 
  PageRespone:
    type: object
    properties :
      path : 
        type: string
        description: name of input file
      type : 
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file
      language :
        type : string
        description: 'ISO 639-1  language code' 
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'
      ocr_output :
        type : array
        description: extrated text, confidence and coordinates
        items :
          allOf:
          - $ref: '#/definitions/Coordinates'
          properties:
            identifier:
              type: string
            text:
              type: string
            words:
              type: array
              description: word level text,coordinates and confidence
              items:
               allOf:
               - $ref: '#/definitions/Coordinates'
               properties:
                identifier:
                  type: string
                text:
                  type: string
          
  Coordinates:
    type: object
    properties:
      top:
        type: integer
        description: y co-ordinate of the bounding box
      left:
        type: integer
        description: x co-ordinate of the bounding box
      width:
        type: integer
        description: width of the bounding box
      height:
        type: integer
        description: height of bounding box
      confidence:
        type: number
        description: detection confidence
  
  
  OcrConfig:
    type: object
    description: configuration for tuning speed and accuracy of ocr mdoule
    properties:
      level:
        type: string
        enum: ['PAGE','LINE','BLOCK' ]
      mode:
        type: string
        enum: ['ACCURRATE','FAST']  
 
  HttpOutput:
    type: object
    properties:
      status:
        type: number
        description: Status code.
  Error:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      http:
        type: object
        description: Final output of this process.
        items:
          $ref: '#/definitions/HttpOutput'
