swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad NMT Fetch Models- API Contract
  description: API to expose all available nmt models for inference generation along with their respective details
  contact:
    name: Kumar Deepak
    email: kumar.deepak@tarento.com

schemes:
  - https
produces:
  - application/json  


paths: 
  /nmt-inference/v1/fetch-models:
    get:
      summary: REST API to generate nmt models information.
      description: GET api to outputs the nmt model information like their model id, source and target language information etc
            
      tags:
      - nmt-fetch-models

      responses:
        200:
          description: On successful completion of the task.
          schema:
            $ref: '#/definitions/nmt_response'
        401:
          description: incorrect input data
          schema:
            $ref: '#/definitions/error_status'
        404:
          description: missing input data
          schema:
            $ref: '#/definitions/error_status'
        500:
          description: interal server/model error
          schema:
            $ref: '#/definitions/error_status'    
  

definitions:
      
  nmt_response:
    type: object
    properties:        
      response_body:
        type: array
        description: A list of models and their details
        items:
          properties:
            created_on:
              type: string
              description: model creation date
            description:
              type: string
              description: model description  
            is_primary:
              type: boolean
              description: whether the model is primary/main model for given language pair(decides for document translation)  
            model_id:
              type: integer
              description: model id of the model 
            model_name:
              type: string
              description: name of the model
            source_language_code:
              type: string
              description: ISO 639-2 language code of the source language
            source_language_name:
              type: string
              description: name of the source language  
            target_language_code:
              type: string
              description: ISO 639-2 language code of the target language
            target_language_name:
              type: string
              description: name of the target language 
            status:
              type: string
              description: whether the model is ACTIVE or INACTIVE  
              enum:
                - "ACTIVE"
                - "INACTIVE"
              
            
      status:
        $ref: '#/definitions/status_obj'
  

  error_status:
    description: response for status code is not 200
    type: object
    properties:
      status:
        $ref: '#/definitions/status_obj'
  
  status_obj:
    type: object
    description: Status object with every request
    properties:
      ok:
        type: string
        enum:
          - "true"
          - "false"
      statusCode: 
        type: integer
        description: http status code
      why:
        type: string
        description: Success message or reason of failure in case of error  
