swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad Block Segmenter
  description: A python based microservice to trigger and orchestrate block level information present in the given file
  contact:
    name: Naresh & Dhiraj, dhiraj.daga@tarento.com
    email: naresh.kumar@tarento.com
schemes:
  - https
basePath: '/api'
paths:
  /v0/block-segmenter:
    post:
      summary: API to extract blocks from the given image file.
      parameters:
        - name: filename
          in: body
          required: true
          schema:
            $ref: '#/definitions/BlockSegmenterRequest'
      tags:
      - Block Segmenter
      responses:
        200:
          description: On successful completion of the job.
          schema:
            $ref: '#/definitions/BlockSegmenterResponse'
        400:
          description: On input errors causing a failure in the job.
          schema:
            $ref: '#/definitions/Error'
definitions:
  BlockSegmenterRequest:
    type : object
    properties:
      files :
        type : array
        description : a list of objets having file name, type and language.
        items :
          $ref : '#/definitions/FilesRequest'
          
          
  BlockSegmenterResponse:
    type : object
    properties:
      files :
        type : array
        description : a list of file level results
        items :
         $ref: '#/definitions/FilesRespone'

  FilesRequest:
    type: object
    properties :
      name : 
        type: string
        description: name of input file
      type : 
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file
      language :
        type : string
        description: 'ISO 639-1  language code' 
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'
      pages :
        type : array
        description: page level word and line coordinates
        items :
          $ref: '#/definitions/PageRequest'
          
  PageRequest:
    type: object
    properties:
      identifier:
        type: string
        description: unique page identifier
      width:
        type: integer
        description:  page width  
      height:
        type: integer
        description:  page height 
      path:
        type: string
        description:  page image name
      words :
        type : array
        description: coordinates of extracted words
        items:
          $ref: '#/definitions/Word'
      lines :
        type : array
        description: coordinates and attributes extracted lines
        items:
          $ref: '#/definitions/Line'
        
      layout : 
        type: array
        description: class and coordinates of layout units
        items:
          $ref: '#/definitions/Layout'
          
          
 
 
  FilesRespone:
    type: object
    properties :
      name : 
        type: string
        description: name of input file
      type : 
        type: string
        description: type of input file
      identifier:
        type: string
        description: unique identifier for a file
      language :
        type : string
        description: 'ISO 639-1  language code' 
      ocr_config:
        type: object
        description: configuration for tuning speed and accuracy of ocr mdoule
        $ref: '#/definitions/OcrConfig'
      pages :
        type : array
        description: page level word, line and block coordinates with layout class
        items :
          $ref: '#/definitions/PageResponse'
 
  PageResponse:
    type: object
    properties:
      identifier:
        type: string
        description: unique page identifier
      width:
        type: integer
        description:  page width  
      height:
        type: integer
        description:  page height 
      path:
        type: string
        description:  page image name
      blocks :
        type : array
        description: coordinates of extracted blocks
        items:
          $ref: '#/definitions/Block'
 
  Block:
    type: object
    properties:
      coordinates:
        type: object
        description: block coordinates extracted after applying visual break condition on layout
        items:
          $ref: '#/definitions/Coordinates'
      identifier:
        type: string
        description: unique identifier for block
      class:
          description: category of detected layout unit
          type: string
          enum : ['TEXT', 'IMAGE', 'TABLE', 'SEPARATOR', 'MATHEMATICAL_FORMULA', 'OTHER']
      text:
        type: string
        description:  collated text at block level 
      font_size:
        type: integer
        description: font size
      font_family:
        type: string
        description: font family of extracted text
      lines :
        type : array
        description: coordinates and attributes of extracted lines
        items:
          $ref: '#/definitions/Line'

      words :
        type : array
        description: coordinates of extracted words
        items:
          $ref: '#/definitions/Word'
  
  Layout:
    type: object
    properties:
      coordinates:
          type: object
          description:  coordinates and confidence extracted by layout unit
          $ref: '#/definitions/Coordinates'
      class:
          description: category of detected layout unit
          type: string
          enum : ['TEXT', 'IMAGE', 'TABLE', 'SEPARATOR', 'MATHEMATICAL_FORMULA', 'OTHER']
      identifier:
        type: string
        description: unique identifier
        
          
  Line:
    type: object
    properties:
      text:
        type: string
        description:   extracted text 
      coordinates:
        type: object
        description: line coordinates extracted by craft
        $ref: '#/definitions/Coordinates'
      
      font_size:
        type: integer
        description: font size
      font_family:
        type: string
        description: font family of extracted text
      
      identifier:
        type: string
        description: unique identifier for line
      attribute:
        type: string
        enum: ['HEADER', 'FOOTER', 'NONE']
     
  Word:
    type: object
    properties:
      identifier:
        type: string
        description: unique identifier for word
      text:
        type: string
        description:   extracted text 
      ocr_confidence:
        type : number
        description: confidence of OCR tool

      font_size:
        type: integer
        description: font size
      font_family:
        type: string
        description: font family of extracted text
      
      attributes:
        type: array
        items:
          type: string
          enum: ['BOLD','ITALIC','UNDERLINE']

      coordinates:
        type: object
        description: word coordinates extracted by craft
        $ref: '#/definitions/Coordinates'

          
  Coordinates:
    type: object
    properties:
      top:
        type: integer
        description: y co-ordinate of the bounding box
      left:
        type: integer
        description: x co-ordinate of the bounding box
      width:
        type: integer
        description: width of the bounding box
      height:
        type: integer
        description: height of bounding box
      confidence:
        type: number
        description: detection confidence
  
  
  OcrConfig:
    type: object
    description: configuration for tuning speed and accuracy of ocr mdoule
    properties:
      level:
        type: string
        enum: ['PAGE','LINE','BLOCK' ]
      mode:
        type: string
        enum: ['ACCURRATE','FAST']  
 
  HttpOutput:
    type: object
    properties:
      status:
        type: number
        description: Status code.
  Error:
    type: object
    properties:
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      http:
        type: object
        description: Final output of this process.
        items:
          $ref: '#/definitions/HttpOutput'
