openapi: 3.0.0
info:
  title: Anuvaad Google Vision Document Digitization
  description: A python based microservice to trigger and orchestrate block level
    information present in the given file
  contact:
    name: Naresh & Dhiraj, dhiraj.daga@tarento.com
    email: naresh.kumar@tarento.com
  version: 1.0.0
servers:
  - url: /api
paths:
  /v0/10/document-digitize:
    post:
      tags:
        - digitize
      summary: API to digitize scanned documents.
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/DigitizationRequest"
        required: true
      responses:
        "200":
          description: On successful completion of the job.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/DigitizationResponse"
        "400":
          description: On input errors causing a failure in the job.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ErrorCode"
      x-codegen-request-body-name: filename
components:
  schemas:
  
    DigitizationRequest:
      type: object
      properties:
        files:
          type: array
          description: a list of objects having file, file_config and its pages
          items:
            type: object
            properties:
              file:
                $ref: "#/components/schemas/File"
              file_config:
                $ref: "#/components/schemas/FileConfig"
          
    DigitizationResponse:
      type: object
      properties:
        outputs:
          type: array
          description: a list of objects having file, file_config and its pages
          items:
            type: object
            properties:
              file:
                $ref: "#/components/schemas/File"
              file_config:
                $ref: "#/components/schemas/FileConfig"
              pages:
                type: array
                description: page level paragraph, line, word  and symbol information
                items:
                  $ref: "#/components/schemas/Page"
    
    File:
      type: object
      properties:
        name:
          type: string
          description: name of input file
        type:
          type: string
          description: type of input file
        identifier:
          type: string
          description: unique identifier for a file generated by the file converter module.
    
    FileConfig:
      type: object
      properties:
        languages:
          type: array
          description: list of ISO 639-1  language code
          items:
            type: string
    
    Page:
      type: object
      properties:
        identifier:
          type: string
          description: unique page identifier
        boundingbox:
          type: object
          $ref:  "#/components/schemas/Vertices"
          description: page coordinates
        path:
          type: string
          description: optional placeholder to hold image path of the page
        resolution:
          type: integer
          description: dpi of the page image
        regions:
          type: array
          description: coordinates of extracted regions
          items:
            $ref: "#/components/schemas/Region"
    
    Region:
      type: object
      properties:
        boundingbox:
          type: object
          $ref:  "#/components/schemas/Vertices"
          description: region coordinates
        identifier:
          type: string
          description: unique identifier for region
          format: uuid4
        class:
          type: string
          description: class of detected region
          enum:
            - PARA
            - LINE
            - IMAGE
            - TABLE
            - TABLE_CELL
            - SEPARATOR
            - MATHEMATICAL_FORMULA
            - HEADER
            - FOOTER
            - BGIMAGE
        path:
          type: string
          description: optional placeholder to hold image path of the region
        regions:
          type: array
          description: various visual objects present on the page
          items:
              oneOf:
                - $ref: '#/components/schemas/Region'
                - $ref: '#/components/schemas/DataRegion'
      required:
        - boundingbox
        - identifier
        - class
        - regions
    
    DataRegion:
      type: object
      required:
        - boundingbox
        - identifier
        - confidence
        - class
        - text
        - font
      properties:
        boundingbox:
          type: object
          $ref:  "#/components/schemas/Vertices"
          description: region coordinates extracted
        identifier:
          type: string
          description: unique identifier for region
          format: uuid4
        language:
          type: string
          description: language of the extracted text
        confidence:
          type: number
          description: confidence of the extracted text
        class:
          type: string
          description: class of detected region
          enum:
            - WORD
            - SYMBOL
            - SUPERSCRIPT
            - SUBSCRIPT
        text:
          type: string
          description: collated text at region level or class specific metadata
        font:
          $ref: "#/components/schemas/Font"
      
  
    Vertices:
      type: array
      description: list of vertex object
      items:
        $ref: '#/components/schemas/Vertex'
    
    Vertex:
      type: object
      description: coordinate of a point, X & Y
      required:
        - x
        - y
      properties:
        x:
          type: number
        y:
          type: number
      
    Font:
      type: object
      properties:
        family:
          type: string
          description: font family
        size:
          type: number
          description: font size
        style:
          type: string
          description: font style like BOLD, ITALIC, REGULAR
          enum:
            - BOLD
            - ITALIC
            - REGULAR
    
    ErrorCode:
      type: object
      properties:
        code:
          type: integer
          description: status code
          enum:
            - FILE_NOT_FOUND
            - FILE_FORMAT_NOT_SUPPORTED
            - OCR_SERVICE_NOT_AVAILABLE
            - UNAUTHORIZED_ACCESS
            - INAPPROPRIATE_DPI_RECEIVED
            
        message:
          type: string
          description: human understandable format
      required:
        - code
        - message
    
    HttpOutput:
      type: object
      properties:
        ok:
          type: boolean
          description: request successful indicator.
        why:
          type: string
          description: Response message.
        status:
          type: object
          description: overall operation status
          $ref: '#/components/schemas/ErrorCode'
        data:
          type: integer
          description: should be null object
          $ref: '#/components/schemas/DigitizationResponse'
          
