swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad Document Converter - API Contract
  description: A python based microservice to trigger and orchestrate the document converter part of anuvaad-extractor.
  contact:
    name: Kumar Deepak
    email: kumar.deepak@tarento.com

schemes:
  - https
basePath: '/api'




paths: 
  /v0/document-converter:
    post:
      summary: REST API to convert json into docx file.
      description: This api takes file data as json and convert it into docx file and then save it in upload folder in server, it's an sync api.
      parameters:
        - name: request
          in: body
          required: true
          description: Request format accepted by this API.
          schema:
            $ref: '#/definitions/Request'
            
      tags:
      - Document Converter

      responses:
        200:
          description: On successful completion of the job.
          schema:
            $ref: '#/definitions/Response'
        400:
          description: On input errors causing a failure in the job.
          schema:
            $ref: '#/definitions/Error'
    


definitions:
        
  HttpOutput:
    type: object
    properties:
      status:
        type: number
        description: Status code. 



  Request:
    type: object
    properties:
      record_id:
        type: string
        description: Record id for the file to be converted.
      user_id:
        type: string
        description: user id to access the data from content-handler db.
          


        
  Response:
    type: object
    properties: 
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      translated_document:
        type: string
        description: translated document name.
      http:
        type: object
        description: Final output of this process.
        example:
          $ref: '#/definitions/HttpOutput'
        

        
        
  Error:
    type: object
    properties:        
      ok:
        type: boolean
        description: request successful indicator.
      why:
        type: string
        description: Response message.
      http:
        type: object
        description: Final output of this process.
        example: 
          $ref: '#/definitions/HttpOutput'