openapi: 3.0.3

info:
  title: Anuvaad File Converter 
  description: |-
    A python based microservice to trigger and orchestrate the file handler part of anuvaad-extractor.
  contact:
    email: nlp-nmt@tarento.com
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
  version: XX.XX.XX

externalDocs:
  description: Find out more of Anuvaad
  url: http://anuvaad.org

servers:
  - url: https://users-auth.anuvaad.org/anuvaad-etl/file-converter/
    description: Anuvaad File Uploader

tags:
  - name: File Converter
    description: (APIs related to converting the file format)

paths: 

  /v0/convert-pdf:
    post:
      tags:
        - File Converter
      summary: REST API to convert files to pdf.
      description: This api takes file name and convert it to pdf, it's an sync api.
      requestBody:
        $ref: '#/components/requestBodies/FileConverterRequest'
        
      responses:
        '200':  
          description: on successful conversion of the file.

          $ref: '#/components/responses/SuccessResponse'
        '400':
          description: on error
          $ref: '#/components/responses/Error'
      security:
        - auth-token: [] 



components:
  
  requestBodies:

    FileConverterRequest:
      description: File id for the file to be converted.
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              filename:
                type: string
                description: file to be converted.
                example: filename.pdf

  responses:

    SuccessResponse:
      description: on successful conversion
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                type: integer
                description: count of the file
                example: 0
              data:
                type: string
                description: converted file name
                example: cd95c0c8-aba9-4660-a9c7-9b041b1c937e.pdf
              http:
                type: object
                properties:
                  status:
                    type: integer
                    description: current status of the file
                    example: 200
              ok:
                type: boolean
                example: true
              why:
                type: string
                description: updation of the request
                example: request successful

    Error:
      description: error on conversion of the file.
      content:
        application/json:
          schema:
            type: object
            properties:
              ok:
                type: boolean
                example: false
              why:
                type: string
                description: updation of the request
                example: not permitted
              http:
                type: object
                properties:
                  status:
                    type: integer
                    description: current status of the file
                    example: 400
              
  securitySchemes:
    auth-token:
      type: apiKey
      name: auth-token
      in: header  

