WorkflowConfigs:

  - workflowCode: DP_WFLOW_01
    description: Transforms the input, extracts the paragraphs, tokenises into sentences, aligns the corp.    
    useCase: CORP-ALIGN
    sequence:
    - order: 0
      tool:
      - name: TRANSFORMER
        description: Accepts pdfs/images and converts using pdf2html or ocr.
        kafka-input:
        - topic: anuvaad-dp-tools-transformer-input
          partitions: 2
          keys: trandformer-input-key-one, trandformer-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-transformer-output
          partitions: 2
          keys: trandformer-output-key-one, trandformer-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: EXTRACTOR
        description: Accepts html/ocr outputs and extracts paragraphs.
        kafka-input:
        - topic: anuvaad-dp-tools-extractor-input
          partitions: 2
          keys: extractor-input-key-one, extractor-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-extractor-output
          partitions: 2
          keys: extractor-output-key-one, extractor-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENIZER
        description: Accepts paragraphs and tokenised them into sentences.
        kafka-input:
        - topic: anuvaad-dp-tools-tokenizer-input
          partitions: 2
          keys: tokenizer-input-key-one, tokenizer-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokenizer-output
          partitions: 2
          keys: tokenizer-output-key-one, tokenizer-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: ALIGNER
        description: Accepts sets of parallel sentences and aligns them.
        kafka-input:
        - topic: anuvaad-dp-tools-aligner-input
          partitions: 2
          keys: aligner-input-key-one, aligner-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-aligner-output
          partitions: 2
          keys: aligner-output-key-one, aligner-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true
      
      
      
    
      
  - workflowCode: DP_WFLOW_02
    description: Transforms the input, extracts the paragraphs. 
    useCase: TEXT-EXTRACTOR
    sequence:
    - order: 0
      tool:
      - name: TRANSFORMER
        description: Accepts pdfs/images and converts using pdf2html or ocr.
        kafka-input:
        - topic: anuvaad-dp-tools-transformer-input
          partitions: 2
          keys: trandformer-input-key-one, trandformer-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-transformer-output
          partitions: 2
          keys: trandformer-output-key-one, trandformer-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: EXTRACTOR
        description: Accepts html/ocr outputs and extracts paragraphs.
        kafka-input:
        - topic: anuvaad-dp-tools-extractor-input
          partitions: 2
          keys: extractor-input-key-one, extractor-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-extractor-output
          partitions: 2
          keys: extractor-output-key-one, extractor-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true



      
  - workflowCode: DP_WFLOW_03
    description: Transforms the input.
    useCase: INPUT-TRANSFORM
    sequence:
    - order: 0
      tool:
      - name: TRANSFORMER
        description: Accepts pdfs/images and converts using pdf2html or ocr.
        kafka-input:
        - topic: anuvaad-dp-tools-transformer-input
          partitions: 2
          keys: trandformer-input-key-one, trandformer-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-transformer-output
          partitions: 2
          keys: trandformer-output-key-one, trandformer-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true

      
      
      
      
  - workflowCode: DP_WFLOW_04
    description: Transforms the input, extracts the paragraphs, tokenises into sentences.
    useCase: TEXT-TOKENIZER
    sequence:
    - order: 0
      tool:
      - name: TRANSFORMER
        description: Accepts pdfs/images and converts using pdf2html or ocr.
        kafka-input:
        - topic: anuvaad-dp-tools-transformer-input
          partitions: 2
          keys: trandformer-input-key-one, trandformer-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-transformer-output
          partitions: 2
          keys: trandformer-output-key-one, trandformer-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: EXTRACTOR
        description: Accepts html/ocr outputs and extracts paragraphs.
        kafka-input:
        - topic: anuvaad-dp-tools-extractor-input
          partitions: 2
          keys: extractor-input-key-one, extractor-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-extractor-output
          partitions: 2
          keys: extractor-output-key-one, extractor-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 2
      tool:
      - name: TOKENIZER
        description: Accepts paragraphs and tokenised them into sentences.
        kafka-input:
        - topic: anuvaad-dp-tools-tokenizer-input
          partitions: 2
          keys: tokenizer-input-key-one, tokenizer-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokenizer-output
          partitions: 2
          keys: tokenizer-output-key-one, tokenizer-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true
      
# 4 different worklfows have been defined here for better understanding.

#Definitions:
workflowCode: Unique Identifier of the workflow definition.
useCase: Identifier of the use case for which this workflow is defined.
sequence: Sequence of tools that will be in play as part of this workflow.
order: Order of execution of that partiuclar tool
tool: Configs for that particular tool
name: Name of the tool in the pipeline
kafka-input: Topic configs which triggers the execution of that particular tool.
topic: kakfa topic
parttions: number of partitions of that topic.
keys: comma seperated keys for each partion. Number of keys must be equal to the number of partitions.
assignment: Algorithm with which records are pushed on to the queue using partitions and their keys.
interruptenable: Boolean value to denote if job interrupt call can be made when the process is at this state or not.
endState: Boolean value to denote if the current tool execution is the final state of the workflow or not.
    
  