WorkflowConfigs:


  - workflowCode: DP_WFLOW_T
    description: tokenises paragraphs into sentences.    
    useCase: TOK
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input_1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output_2
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: DP_WFLOW_A
    description: Aligns the input files. 
    useCase: ALIGN
    sequence:
    - order: 0
      tool:
      - name: ALIGNER
        description: Accepts 2 parallel files and alings them into parallel corp for training
        kafka-input:
        - topic: anuvaad-dp-tools-aligner-input-new
          partitions: 2
          keys: aligner-input-key-one, aligner-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-aligner-output-new
          partitions: 2
          keys: aligner-output-key-one, aligner-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: DP_WFLOW_TA
    description: tokenises into sentences, aligns the corp.    
    useCase: TOK-ALIGN
    sequence:
    - order: 0
      tool:
      - name: TOKENISER
        description: Tokenises a given file with paragraphs
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input_1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output_2
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: ALIGNER
        description: Accepts 2 parallel files and alings them into parallel corp for training
        kafka-input:
        - topic: anuvaad-dp-tools-aligner-input-new
          partitions: 2
          keys: aligner-input-key-one, aligner-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-aligner-output-new
          partitions: 2
          keys: aligner-output-key-one, aligner-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: DP_WFLOW_P2H
    description: Converts a pdf into html and image files.    
    useCase: P2H
    sequence:
    - order: 0
      tool:
      - name: PDFTOHTML
        description: Converts a pdf into html and image files
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input_1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output_2
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: DP_WFLOW_H2J
    description: Converts a html files to json 
    useCase: H2J
    sequence:
    - order: 0
      tool:
      - name: HTMLTOJSON
        description: Converts a html files to json
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input_1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output_2
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true


  - workflowCode: DP_WFLOW_P2H2J
    description: Converts a pdf into json.  
    useCase: P2H-H2J
    sequence:
    - order: 0
      tool:
      - name: PDFTOHTML
        description: Converts a pdf into html and image files
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input_1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output_2
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: false
    - order: 1
      tool:
      - name: HTMLTOJSON
        description: Converts a html files to json
        kafka-input:
        - topic: anuvaad-dp-tools-tokeniser-input_1
          partitions: 2
          keys: tokeniser-input-key-one, tokeniser-input-key-two
          assignment: round-robin
        kafka-output:
        - topic: anuvaad-dp-tools-tokeniser-output_2
          partitions: 2
          keys: tokeniser-output-key-one, tokeniser-output-key-two
          assignment: round-robin
      interruptenable: true
      endState: true