swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad ETL - Common Contract
  description: This file contains structure of the common objects shared between modules of the pipeline
  contact:
    name: Vishal Mahuli
    email: vishal.mahuli@tarento.com


definitions:

  File:
    type: object
    properties:
      path:
        type: string
        description: Name of the file. This will be obtained in the output of the file upload API exposed by the anuvaad system. 
      type:
        type: string
        description: type of the file.
        enum:
          - PDF
          - IMAGE
          - TEXT
          - CSV
      locale:
        type: string
        description: The locale of the file. Meaning, in which language is the uploaded file. For instance, 'en' for English, 'hi' for Hindi etc.
        format: varchar
      model:
        type: object
        description: Model object as returned from fetch-model API, defined by NMT.
      config:
        type: object
        description: config object as defined by OCR.
      context:
        type: string
        description: Context to which this file belongs. 
        
        
  TaskInput:
    type: object
    properties:
      jobID:
        type: string
        description: Alpha Numeric JOB ID that is generated by wf manager.      
      workflowCode:
        type: string
        description: Alpha Numeric string that identifies a configured workflow. This is mentioned in the config file and attached by the user.
      tool:
        type: string
        description: Name of the current tool. Attached by WF Manager.
        enum:
          - PDFTOHTML
          - HTMLTOJSON
          - OCR
          - EXTRACTOR
          - TOKENISER
          - ALIGNER
          - NER
      stepOrder:
        type: integer
        description: Order of the current step in order execution of the workflow. Attached by WFM.
      input:
        type: object
        description: JSON of the input as expected by the tool.


  TaskOutput:
    type: object
    properties:
      taskID:
        type: string
        description: Alpha Numeric TASK ID that is generated by the tool
      jobID:
        type: string
        description: Alpha Numeric JOB ID that is generated by wf manager.      
      workflowCode:
        type: string
        description: Alpha Numeric string that identifies a configured workflow. This is mentioned in the config file and attached by the user.
      tool:
        type: string
        description: Name of the current tool. Attached by WF Manager.
        enum:
          - PDFTOHTML
          - HTMLTOJSON
          - OCR
          - EXTRACTOR
          - TOKENISER
          - ALIGNER
          - NER
      stepOrder:
        type: integer
        description: Order of the current step in order execution of the workflow. Attached by WFM.
      input:
        type: object
        description: JSON of the input as expected by the tool.
      output:
        type: object
        description: JSON of the output as generated by the tool.
      status:
        type: string
        description: Status of execution of the current tool.
        enum:
          - SUCCESS
          - FAILED
      state:
        type: string
        description: State to which workflow reaches after execution of the current tool.
        enum:
          - INGESTED
          - PDF-TO-HTML-PROCESSED
          - HTML-TO-JSON-PROCESSED
          - OCR-PROCESSED
          - PARAGRAPH-EXTRACTED
          - SENTENCES-TOKENISED
          - SENTENCES-ALIGNED
          - NER-PROCESSED
      taskStartTime:
        type: integer
        description: 13 digit Epoch value of the timestamp at instance of start of the task.
      taskEndTime:
        type: integer
        description: 13 digit Epoch value of the timestamp at instance of end of the task.
      error:
        type: object
        descrption: If an error occurs in the flow, the error JSON will be attached here.
        $ref: '#/definitions/Error'
        
        
  User:
    type: object
    properties:
      name:
        type: string
        description: Name of the user
      id:
        type: string
        description: Unique ID of the user. It can be the ID used to log into anuvaad's system.
      email:
        type: string
        description: Email ID of the user.
        
        
  Error:
    type: object
    properties:
      errorID:
        type: string
        description: Unique ID generated for this error.
      jobID:
        type: string
        description: ID of the job within which the error occured.
      taskID:
        type: string
        description: ID of the task within which the error occured.
      state:
        type: string
        description: Processing state of the job just before the error.
      httpCode:
        type: string
        description: Http Code of the error
      errorMsg:
        type: string
        description: This is the machine generated error message like TypeError, ValueError etc with line number.
      cause:
        type: string
        description: This is the cause of the error in a user understandable format that is defined by the developer.
      timeStamp:
        type: number
        description: epoch time at the instant of error.
