swagger: "2.0"
info:
  version: 1.0.0
  title: Anuvaad Worfklow Manager - API Contract
  description: A python based microservice to trigger and orchestrate the workflow of the anuvaad-etl pipeline. This service will expose REST APIs for workflow related activities on the other hand will also be plugged into the system as a consumer that picks records posted onto the Kafka Queue in order to perform workflow related activities.
  contact:
    name: Vishal Mahuli
    email: vishal.mahuli@tarento.com

schemes:
  - https
basePath: '/anuvaad-etl/wf-manager'




paths: 
  /v1/workflow/initiate:
    post:
      summary: REST API to register and trigger the workflow.
      description: This API accepts either pdf or images and initiates the workflow, which runs through a pipeline. This is an async process.
      parameters:
        - name: request
          in: body
          required: true
          description: Request format accepted by this API.
          schema:
            $ref: '#/definitions/WFInitiateRequest'
            
      tags:
      - Initiate

      responses:
        202:
          description: On successful initiation of the job.
          schema:
            $ref: '#/definitions/WFInitiateResponse'
        400:
          description: On input errors causing a failure in the job.
          schema:
            $ref: 'https://raw.githubusercontent.com/project-anuvaad/anuvaad/wfmanager_feature/anuvaad-etl/docs/common-contract.yml#/definitions/Error'
        500:
          description: On system level errors causing failure in the job.
          schema:
            $ref: 'https://raw.githubusercontent.com/project-anuvaad/anuvaad/wfmanager_feature/anuvaad-etl/docs/common-contract.yml#/definitions/Error'
  


          
  /v1/workflow/jobs/search/bulk:
    post:
      summary: REST API to search wf job status.
      description: This API provides a facility to search wf jobs based on various criteria. Result is sorted default on startTime descending.
      parameters:
        - name: request
          in: body
          required: true
          description: Request format accepted by this API.
          schema:
            $ref: '#/definitions/WFJobSearchRequest'
            
      tags:
        - Search
        
      responses:
        200:
          description: Either an empty or a non-empty array of responses.
          schema:
            type: array
            items:
              $ref: '#/definitions/WFJobSearchResponse'
              
              
              

  /v1/workflow/configs/search:
    get:
      summary: REST API to search wf configs from the config file.
      description: This API provides a facility to search wf configs.
      tags:
        - Config Search
      responses:
        200:
          description: Either an empty or a non-empty array of config JSONs.




definitions:

  WFInitiateRequest:
    type: object
    properties:
      input:
        type: array
        items:
          type: object
          $ref: 'https://raw.githubusercontent.com/project-anuvaad/anuvaad/wfmanager_feature/anuvaad-etl/docs/common-contract.yml#/definitions/File'
        description: Details of the files that are to be passed to the wf.
      workflowCode:
        type: string
        description: Code of the workflow that has to be picked to process this input. These workflows are configured at the application level.
        
  WFInitiateResponse:
    type: object
    properties:
      input:
        type: object
        description: Details of the request sent.
        $ref: '#/definitions/WFInitiateRequest'        
      jobID:
        type: string
        description: A unique job ID generated for this workflow.
      status:
        type: string
        description: Current status of the workflow
        enum:
          - START
          - INPROGRESS
          - FAILED
          - INTERRUPTED
          - COMPLETED
      state:
        type: string
        description: Current state of the workflow
        enum:
          - FILE-CONVERTED
          - BLOCKS-MERGED
          - SENTENCE-TOKENISED
          - SENTENCES-ALIGNED
          - TRANSLATED
      output:
        type: object
        description: Intermediate or final output of the process. If the status = COMPLETE and the state = PROCESSED, this output is considered to be the final output, intermediate otherwise. It is a JSON.
      taskDetails:
        type: array
        items:
          type: object
          $ref: 'https://raw.githubusercontent.com/project-anuvaad/anuvaad/wfmanager_feature/anuvaad-etl/docs/common-contract.yml#/definitions/TaskOutput'
        description: List of JSONs that explains output of each task involved in the workflow
      error:
        type: object
        description: Incase the job fails due to an error in of the child tasks, that error will be capture here for the benefit of the user.
        $ref: 'https://raw.githubusercontent.com/project-anuvaad/anuvaad/wfmanager_feature/anuvaad-etl/docs/common-contract.yml#/definitions/Error'
      startTime:
        type: number
        description: 13 digit epoch of the start time.
      endTime:
        type: number
        description: 13 digit epoch of the end time.

          
  WFJobSearchRequest:
    type: object
    properties:
      jobIDs:
        type: array
        items:
          type: string
        description: Unique IDs of the etl-wf jobs
      userIDs:
        type: array
        items:
          type: string
        description: Unique IDs of the users who have initiated the etl-wf jobs.
      statuses:
        type: array
        items:
          type: string
          enum:
            - START
            - INPROGRESS
            - FAILED
            - INTERRUPTED
            - COMPLETED
        description: Statuses of the etl-wf jobs.
      taskDetails:
        type: boolean
        description: The response will have taskDetails array if this value is set to 'True', otherwise the list will be empty.
      error:
        type: boolean
        description: The response will have error details by default but can be excluded by setting this key to 'False'.
      workflowCodes:
        type: array
        items:
          type: string
        description: Workflow Codes of the etl-wf jobs.
      offset:
        type: number
        description: Starting index of the paginated result
      limit:
        type: number
        description: Count of records to be returned starting from the offset
        
        
  WFJobSearchResponse:
    type: object
    properties:
      response:
        type: array
        items:
          type: object
          $ref: '#/definitions/WFInitiateResponse'
        description: List of jobs returned for the criteria.
      
